security:
    encoders:
        Fsb\Proxy\AppBundle\Model\User:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            iterations:           1000000
            encode_as_base64:     true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            id: fsb_proxy_app.provider.yaml_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|fonts|js)/
            security: false

        fsb_proxy_app_login:
            pattern:  ^/login$
            security: false

        fsb_proxy_app:
            pattern:  ^/
            anonymous: ~
            provider: users
            form_login:
                check_path: fsb_proxy_app_login_check_page
                login_path: fsb_proxy_app_login_page
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path:   fsb_proxy_app_logout_page
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
