security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            iterations:           1000000
            encode_as_base64:     true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    guest:
                        password: MGbSREk1CGtz+hia9ztTzDbkbbB11a5Sk3HFC630jcvnh8IlgNlnMw==
                        roles: [ 'ROLE_USER' ]
                    bobby:
                        password: 3p3nDyCXHYQt4qDnpglv3kfOgLcbnSOHD/+IdakJWGWFlgxsUTIewg==
                        roles: [ 'ROLE_USER' ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        fsb_proxy_app_login:
            pattern:  ^/login$
            security: false

        fsb_proxy_app:
            pattern:  ^/
            anonymous: ~
            form_login:
                check_path: fsb_proxy_app_login_check_page
                login_path: fsb_proxy_app_login_page
            logout:
                path:   fsb_proxy_app_logout_page
                target: fsb_proxy_app_proxy_page

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
