fsb_proxy_app_login_page:
    path:  /login
    defaults:
        _controller: FsbProxyAppBundle:Security/Authentication:login
    methods: [GET]

fsb_proxy_app_login_check_page:
    path:  /login_check
    methods: [POST]

fsb_proxy_app_logout_page:
    path:  /logout
    methods: [GET]

fsb_proxy_app_proxy_page:
    path:     /{uri}
    defaults:
        _controller: FsbProxyAppBundle:Rest:proxy
    requirements:
        uri: .*
