parameters:
    fsb_proxy_app.provider.yaml_user_provider.class: Fsb\Proxy\AppBundle\Provider\YamlUserProvider

services:
    fsb_proxy_app.provider.yaml_user_provider:
        public: false
        class: %fsb_proxy_app.provider.yaml_user_provider.class%
        arguments: [%users_provider_file_path%]

    http.client:
        alias: guzzle.client

